### ISSUE TITLE
Stopped working after upgraded HA to 2025.6

### ISSUE THREAD

**Issue by superpanjy** [dewgenenny/hagocoax#6]
Last logged: 5:34:04 PM

Error setting up entry GoCoax (192.168.1.247) for gocoax

Error setting up entry GoCoax (192.168.1.251) for gocoax

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gocoax/__init__.py", line 28, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by superpanjy** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 8:55:49 PM (1 occurrence)
Last logged: 8:55:49 PM

Error setting up entry GoCoax (192.168.1.245) for gocoax
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gocoax/__init__.py", line 28, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by jb0767** [comment]
Same issue here. Any solution yet?

**Comment by dewgenenny** [comment]
Hey @superpanjy and @jb0767 can you try with the latest update? Seems to have fixed any errors for me.

**Comment by jb0767** [comment]
Hey, yes the latest update works fine. Thank you!
